--- !map:Settings 
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"003": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"024": 
  layout: 
    fields: 
    - - a
"035": 
  layout: 
    fields: 
    - - a
    - - z
    - - "9"
"040": 
  layout: 
    fields: 
    - - b
    - - e
"043": 
  layout: 
    fields: 
    - - a
"056": 
  layout: 
    fields: 
    - - a
"079": 
  layout: 
    fields: 
    - - b
    - - q
    - - u
    - - v
"100": 
  layout: 
    fields: 
    - - t
"380": 
  layout: 
    fields: 
    - - a
"382": 
  layout: 
    fields: 
    - - "9"
"383": 
  layout: 
    fields: 
    - - a
    - - b
    - - c
"384": 
  layout: 
    fields: 
    - - a
"400": 
  layout: 
    fields: 
    - - t
"500": 
  layout: 
    fields: 
    - - a
"530": 
  layout: 
    fields: 
    - - a
"540": 
  layout: 
    fields: 
    - - a
"548": 
  layout: 
    fields: 
    - - a
"550": 
  layout: 
    fields: 
    - - a
"667": 
  layout: 
    fields: 
    - - "5"
"670": 
  layout: 
    fields: 
    - - a
"675": 
  layout: 
    fields: 
    - - a
"678": 
  layout: 
    fields: 
    - - b
"912": 
  layout: 
    fields: 
    - - a
