--- !map:ActiveSupport::HashWithIndifferentAccess
_default_unknown_labels: true
main_work:
  label: gnd.main_work
variants:
  label: gnd.variants
references:
  label: gnd.references
codes:
  label: gnd.codes
relations:
  label: gnd.relations
control:
  label: gnd.control
unmatched:
  label: gnd.ungrouped
'000':
  label: records.leader
'001':
  label: records.rism_id_number
'003':
  label: records.control_number_identifier
'005':
  label: records.date_time_last_transaction
'024':
  fields:
    '2':
      label: gnd.source_number_code
    a:
      label: gnd.standard_number_code
  label: records.other_standard_identifier
'100':
  fields:
    a:
      label: gnd.title
    d:
      label: gnd.years_birth_death
    m:
      label: gnd.scoring_summary
    n:
      label: gnd.opus_thematic_index_number
    r:
      label: gnd.key_or_mode
    t:
      label: gnd.title_of_work
  label: gnd.heading
'380':
  fields:
    a:
      label: gnd.instrument
  label: gnd.instrument