--- !map:Settings 
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"024": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - "2"
      - values: 
        - "BNE"
        - "BNF"
        - "DNB"
        - "ICCU"
        - "ISNI"
        - "LC"
        - "NLP"
        - "NKC"
        - "SWNL"
        - "VIAF"
        - "WKP"
        default: "VIAF"
        editor_partial: subfield_select
      - cols: 2
    columns: 4
"033": 
  layout: 
    fields: 
    - - indicator
      - editor_partial: subfield_indicator
    - - a
"040": 
  layout: 
    fields: 
    - - a
      - cols: 2
    - - c
      - cols: 2
    - - d
      - cols: 2
    - - b
      - cols: 2
    columns: 4
"100":
  new_window: people
  new_window_field: full_name_equals
  layout: 
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
        allow_new: true
    - - d
      - autocomplete_extra: life_dates
    - - m
    - - n
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "100r"
    - - t
    columns: 4
  tag_params:
      100r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1tt"
      - "2tt"
      - "3tt"
      - "4tt"
      - "5tt"
      - "6tt"
      - "7tt"
      - "8tt"
      - "9tt"
      - "10tt"
      - "11tt"
      - "12tt"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
"380": 
  allow_new: true
  new_window: standard_terms
  layout: 
    fields: 
    - - "a"
      - type: standard_term
        editor_partial: subfield_secondary
      - cols: 4
    columns: 4
"400":
  new_window: people
  new_window_field: full_name_equals
  layout: 
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
        allow_new: true
    - - d
      - autocomplete_extra: life_dates
    - - m
    - - n
    - - r
    - - t
    columns: 4
"500": 
  allow_new: true
  new_window: people
  layout: 
    fields: 
    - - "a"
      - type: person
        editor_partial: subfield_secondary
      - cols: 4
    - - d
    - - e
    columns: 4
"548": 
  layout: 
    fields: 
    - - a
      - growfield: true
    - - i
      - values:
        - "Date of origin"  
        editor_partial: subfield_select
"667": 
  layout: 
    fields: 
    - - a
      - cols: 2
    columns: 2
"670": 
  allow_new: true
  new_window: publications
  layout: 
    fields: 
    - - "a"
      - type: publication
        editor_partial: subfield_secondary
      - cols: 4
    - - "b"
      - cols: 2
    columns: 4
"675": 
  allow_new: true
  new_window: publications
  layout: 
    fields: 
    - - "a"
      - type: publication
        editor_partial: subfield_secondary
      - cols: 4
    columns: 4
"680": 
  layout: 
    fields: 
    - - a
      - growfield: true
"700":
  allow_new: true
  new_window: people
  layout:
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
  tag_params: 
    relator_codes: 
    - cmp
    - dte
    - asn
    - lbt
    - lyr
    - oth
"710":
  new_window: institutions
  new_window_field: name_equals
  layout: 
    fields: 
    - - a
      - type: institution
        editor_partial: subfield_secondary
        allow_new: true
    - - b
    - - g
      - editor_partial: subfield_select_codes
        codes_reference: "codes"
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
  tag_params: 
    codes:
      - "Ascertained"
      - "Alleged"
      - "Conjectural"
      - "Doubtful"
      - "Misattributed"
    relator_codes: 
      - dte
      - oth
"747": 
  allow_new: true
  new_window: liturgical_feasts
  layout: 
    fields: 
    - - "a"
      - type: liturgical_feast
        editor_partial: subfield_secondary
      - cols: 4
    columns: 4
