--- !map:Settings
server:
  - validate_user_abilities
client:
  "100": 
    tags:
      "0": required
      a: required
  "240":
    tag_overrides:
      exclude:
        m:
        - collection
        - theoretica_source
        - libretto_edition 
        - composite_volume
    tags:
      "0": mandatory
      m: required, warning
  "245": 
    tags:
      a: mandatory
  "260": 
    tags:
      c: required
  "300": 
    tags:
      a: required
  "593":
    tag_overrides:
      exclude:
        "a":
        - collection
        - composite_volume
    tags:
      "a": mandatory
  "594": 
    tags:
      b: required
  "650":
    tag_overrides:
      exclude:
        "0":
        - collection
        - composite_volume
    tags:
      "0": mandatory
  "852":
    tag_overrides:
      exclude:
        "x":
        - edition
        - edition_content
        - libretto_edition 
    tags:
      c: required, warning
      x: mandatory
  "856": 
    tags:
      z:
        required_if:
          "856": "u"
      x:
        required_if:
          "856": "u"
